postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres
redis:
  addr: localhost
  port: 6379
  password: "123"
  db: 1
mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  dbname: mysql
